<script lang="ts">
    import { _ } from "svelte-i18n";
    import { onMount } from "svelte";
    import { currentPageStore } from "../../../../stores";

    import { Navbar, NavbarBackLink, Block, Button } from "konsta/svelte";

    type Dependency = {
        name: string;
        version: string;
        license: string;
    }

    let dependencies: Dependency[] = [];

    onMount(async function() {
        const response = await fetch('/dependencies.json'); // the file is stored in static and generated by scripts/generate-dependency-acknowledgments.js
        dependencies = await response.json() as Dependency[];
    });
</script>

<style>
    .dependency-info {
        display: flex;
        flex-direction: column;
    }

    .dependency-name {
        font-size: 18px;
        font-weight: bold;
    }

    .more-button-container {
        margin-top: 15px;
    }
</style>

<Navbar title={$_('dependencyAcknowledgments.title')}>
    <NavbarBackLink slot="left" text="Back" onClick={function() {$currentPageStore = 'about'}} />
</Navbar> 

{#each dependencies as dependency}
    <Block strong inset>
        <div class="dependency-info">
            <span class="dependency-name">{dependency.name}</span>
            <span>{$_('dependencyAcknowledgments.version', {values: {value: dependency.version}})}</span>
            <span>{$_('dependencyAcknowledgments.license', {values: {value: dependency.license}})}</span>
            
            <div class="more-button-container">
                <Button small onClick={function() {window.open(`https://www.npmjs.com/package/${dependency.name}`, '_blank')}}>
                    {$_('dependencyAcknowledgments.more')}
                </Button>
            </div>
        </div>
    </Block>
{/each}